services:
  web:
    image: ${DOCKERHUB_USERNAME}/myflask:latest
    environment:
      FLASK_ENV: production
      RIOT_API_KEY: ${RIOT_API_KEY}
      COLLECT_INTERVAL_SEC: ${COLLECT_INTERVAL_SEC}
      COLLECT_REGION: ${COLLECT_REGION}
      COLLECT_PLAYERS: ${COLLECT_PLAYERS}
      COLLECT_PER_PLAYER: ${COLLECT_PER_PLAYER}
    expose:
      - "5000"
    healthcheck:
      # HTTP 200로 체크
      test: ["CMD", "sh", "-c", "wget -qO- http://127.0.0.1:5000/ || wget -qO- http://127.0.0.1:5000"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      web:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/templates:ro
      - ./certbot/config:/etc/letsencrypt          # ← 바인드 유지(OK)
      - ./certbot/www:/var/www/certbot             # ← 바인드 유지(OK)
      # 권장: letsencrypt:/etc/letsencrypt, certbot-www:/var/www/certbot (named volume)
    environment:
      DOMAIN: ${DOMAIN}
    entrypoint:
      - sh
      - -exc
      - |
        envsubst '$DOMAIN' < /etc/nginx/templates/default.http.conf.template > /etc/nginx/conf.d/default.conf
        exec nginx -g 'daemon off;'
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    command:
      - certonly
      - --webroot
      - --webroot-path=/var/www/certbot
      - --non-interactive
      - --agree-tos
      - --email
      - "${LETSENCRYPT_EMAIL}"
      - -d
      - "${DOMAIN}"
    volumes:
      - ./certbot/config:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: "no"

  certbot-renew:
    image: certbot/certbot
    volumes:
      - ./certbot/config:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      sh -c "while true; do
               certbot renew --quiet --deploy-hook 'docker exec nginx nginx -s reload';
               sleep 12h;
             done"
    restart: unless-stopped

# 권장(선택): named volume 사용시
# volumes:
#   letsencrypt:
#   certbot-www:
