services:
  web:
    build: .
    expose:
      - "5000"
    environment:
      - FLASK_ENV=development
      - RIOT_API_KEY=${RIOT_API_KEY}
    volumes:
      - .:/app
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro