
services:
  web:
    image: ${DOCKERHUB_USERNAME}/myflask:latest
    environment:           # ← 컨테이너 내부 환경변수
      FLASK_ENV: production
      RIOT_API_KEY: ${RIOT_API_KEY}
      # 아래 값들은 선택 (스케줄러 사용 시)
      COLLECT_INTERVAL_SEC: ${COLLECT_INTERVAL_SEC:-900}
      COLLECT_REGION: kr
      COLLECT_PLAYERS: ${COLLECT_PLAYERS:-15}
      COLLECT_PER_PLAYER: ${COLLECT_PER_PLAYER:-3}
    expose:
      - "5000"
    healthcheck:
      test: ["CMD", "python", "-c", "import socket,sys; s=socket.socket(); s.settimeout(1); s.connect(('127.0.0.1',5000)); s.close(); sys.exit(0)"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:alpine
    depends_on:
      web:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/templates:ro
      - ./certbot/config:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:           # ← 매핑 형식
      DOMAIN: ${DOMAIN}
    entrypoint:
      - sh
      - -exc
      - |
        envsubst '$DOMAIN' < /etc/nginx/templates/default.http.conf.template \
          > /etc/nginx/conf.d/default.conf
        exec nginx -g 'daemon off;'
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    command:
      - certonly
      - --webroot
      - --webroot-path=/var/www/certbot
      - --non-interactive
      - --agree-tos
      - --email
      - "${LETSENCRYPT_EMAIL}"
      - -d
      - "${DOMAIN}"
    volumes:
      - ./certbot/config:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: "no"

  certbot-renew:
    image: certbot/certbot
    volumes:
      - ./certbot/config:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      sh -c "while true; do
               certbot renew --quiet --deploy-hook 'docker exec nginx nginx -s reload';
               sleep 12h;
             done"
    restart: unless-stopped

volumes:
  certbot-config:
    driver: local
  certbot-www:
    driver: local
